# Generated by Django 6.0.4 on 2026-04-21 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('coding', 'Coding'), ('carriere', 'Carrière'), ('education', 'Éducation'), ('tech', 'Tech'), ('entrepreneuriat', 'Entrepreneuriat'), ('motivation', 'Motivation'), ('outils', 'Outils & Ressources')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
